Merge feauture-signup to branch develop
ampaire/html-forms pull request #2
Opened 2019-08-15 23:39 UTC by ampaire

This Pull request presents html forms for the intuit sign up page

2019-08-16 21:24 UTC, samgaco requested changes
### Hi @ampaire and @Elijahscriptdev :hand: 

### Everything looking nice so far :clap:  some things to work on before we can give you the approval:

* This part here should be composed by text (mint, quickbooks and turbotax) and the logos aligned at the left.
![Screenshot_2019-08-16_23-05-42](https://user-images.githubusercontent.com/34820784/63198265-7a2fb200-c07a-11e9-9ae7-3a7356b9f512.png)
* You could add a **live demo** of the site to your readme file, using https://raw.githack.com/ for example.
* Read on [HTML semantic ](https://www.w3schools.com/html/html5_semantic_elements.asp )elements and implement them in your project. For example, you should use the `<main>` tag for the dominant content in the body of your project.
* Read about [git flow ](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) and apply it for your next projects. (This pull request should be merging to the master branch)

> You will need to create a Pull Request to merge your feature branch with the master branch and submit the link to that Pull Request using a form linked in the lessons’ description. This way, you will get a code review from one of our Technical Support Engineers 

### That's it. Please :pray: submit back for another code review when you are done with these changes :muscle:

2019-08-16 21:24 UTC, samgaco commented on index.html
> +            <img src="images/intuitLogo.png" alt="Intuit Logo">
This image should not contain the texts with the logos below.

2019-08-19 23:39 UTC, stratospherique requested changes
Good effort :clap: and almost done . However, you should fix the following issues:

2019-08-19 23:39 UTC, stratospherique commented on index.html
> +        </main>
the footer should be sibling to main and not a children of it.

2019-08-19 23:39 UTC, stratospherique commented on styles.css
> +}
You can use flex properties to make the logos with their text aligned with the proper spacing. Since you didn't take care of that

2019-08-19 23:48 UTC, stratospherique commented on styles.css
> +}
And that's It. When finished! kindly re-submit your Pull request for another code review. :muscle: :muscle:

2020-09-30 16:33 UTC, merged